# This is a basic workflow to help you get started with Actions

name: Python CI Practice

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python file
        run: python calculator.py

      - name: Run tests
        run: |
          pip install pytest
          pytest
